language: android
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-24
jdk:
- oraclejdk8
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
script:
- adb devices
- "./gradlew assembleDebug"
before_install:
- openssl aes-256-cbc -K $encrypted_cfbef3257026_key -iv $encrypted_cfbef3257026_iv
  -in secrets.xml.enc -out SDK/src/main/res/values/secrets.xml -d
